### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by N8Fear**
This one removes a few compiler warnings.

### CODE REVIEW

**Comment by hryniuk** [comment]
Great. I see some "style" (whitespaces) fixes... We could run `rustfmt` once and set a check (I don't have a right to install Travis here for now) to avoid such issues in the future. I'll review (and merge) this PR (and the other one) in next 24 hours, thanks.

I've created a git hook to check style with `cargo fmt` some time ago. It's quite simple, but you might be interested: https://gist.github.com/hryniuk/e3f4ae34e37947d0ff55a3f63add90f8
Just name it `pre-commit` and place it under `.git/hooks` in your repo.

**Comment by N8Fear** [comment]
Sounds like a great idea. I'm using git for quite a while but never really got into hooks. I guess this is a got chance to get into it.
I also like the idea of getting a "clean" base before that by using rustfmt. 
By the way: I should have stated that this PR depends on #115

**Comment by hryniuk** [comment]
Ok, merged. I'll think about the whole `rustfmt` thing.

**Short info**
I'm here, because I've wanted to use WTFTW and I've shared a few commits to make it work again. Next I asked Simon about futher improvements, but he told me that WTFTW is "deprecated". For me it's a nice project that had a lot of interest and I'm able to continue it, so I've [started to work on XCB port](https://github.com/hryniuk/wtftw/tree/event-loop). In my opinion with more contributors it may live along with other WMs, but we will see. If there is a better WM in Rust, there's a chance I'll move to it.

**Comment by N8Fear** [comment]
I've ran rustfmt just to see what it does and doing it is a big change. There are pros and cons of that - while breaking compatibility with a bunch of possible not upstreamed patches, it would establish a clean baseline...

**Pull request merged**
