### PR TITLE
A bit of refactoring

### PR DESCRIPTION
**Pull request by Victor-Savu**
Hi!

I was wondering if you were ok with the idea of refactoring the pattern
fn foo(x: Bar<a'>, ... ) -> Bar<'a> { ... }
into
fn foo(x: &mut Bar, ...) { ... }

I know the compiler is really good at eliding copies, but my brain is not. I made this change for Bar = WindowManager.
I eliminated a bunch of lifetime specifiers as well.

I know both cases (returning a modified copy and the lifetime specifiers) were probably design decisions and you might be very right to disagree with the changes. In that case, could you please explain the decision so I may learn from your experience?

One more change:
I split up the core module into a separate folder with modules for each type in order to keep the components smaller.

Thanks!

### CODE REVIEW

**Comment by Kintaro** [comment]
First reason was to just try how easy that kind of design would be. But one of the major reasons is method chaining. Stuff like focus_down resolves to self.reverse().focus_up().reverse() and another major decision was closures. The immutable design makes lifetime issues way easier. 

I try to avoid mutability whereever I can, as it keeps the bug count low.

**Comment by Victor-Savu** [comment]
Thanks a lot for the comment!
I totally agree with avoiding mutability wherever possible. However, this specific construct where a function takes an immutable argument and returns a mutated copy seemed to be semantically identical to the borrowing concept in Rust as explained in the book, only (potentially) a bit less efficient.

I haven't tried chaining with borrowing, though: 
```rust
fn foo<'a>(x: &'a mut Bar, ...) -> &'a mut Bar { ... }
```
or better yet
```rust
fn foo<'a>(&`a mut self, ....) -> &'a mut Self { ... }
```

Would it be OK with you if I used my fork for experimenting with such designs? Also, would you be interested in exchanging opinions from time to time (e.g. on the wtftw gitter page)?

**Comment by Kintaro** [comment]
Sure, no problem. I mostly used it to be able to drop the structs into closures and not care about specifically creating copies for that. For example for filtering, mapping, etc.

**Comment by Kintaro** [comment]
Interesting that most of the lifetime specs can be removed...the borrow checker really did improve a lot.

**Comment by Kintaro** [comment]
I took over the core module refactoring. Thanks.

**Pull request closed without merging**
